-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE SEQUENCE "public"."seq_paket_tender_selesai" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_paket_nontender_selesai" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_kontrak" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_rup_paket_anggaran" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_pencatatan_realisasi" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_paket_purchase_old" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_kontrak_nontender" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_bast_nontender" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_bast" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_swakelola_realisasi" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_rup_paket_lokasi" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_rup_paket_anggaran_swakelola" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_paket_purchase" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "paket_purchase" (
	"kd_paket" numeric NOT NULL,
	"no_paket" varchar,
	"nama_paket" varchar,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"satker_id" numeric,
	"nama_satker" varchar,
	"alamat_satker" varchar,
	"npwp_satker" varchar,
	"kd_rup" numeric,
	"nama_sumber_dana" varchar,
	"kode_anggaran" varchar,
	"kd_komoditas" numeric,
	"kd_produk" numeric NOT NULL,
	"kd_penyedia" numeric,
	"kd_penyedia_distributor" numeric,
	"jml_jenis_produk" numeric,
	"kuantitas" numeric,
	"harga_satuan" numeric,
	"ongkos_kirim" numeric,
	"total_harga" numeric,
	"kd_user_pokja" numeric,
	"no_telp_user_pokja" varchar,
	"email_user_pokja" varchar,
	"kd_user_ppk" numeric,
	"ppk_nip" varchar,
	"jabatan_ppk" varchar,
	"tanggal_buat_paket" timestamp,
	"tanggal_edit_paket" timestamp,
	"deskripsi" varchar,
	"status_paket" varchar,
	"paket_status_str" varchar,
	"catatan_produk" varchar,
	"kd_provinsi_wilayah_harga" integer,
	"kd_kabupaten_wilayah_harga" integer,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_paket_purchase'::regclass) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tokodaring_realisasi" (
	"jenis_transaksi" varchar,
	"kategori" varchar,
	"kd_klpd" varchar,
	"kd_satker" varchar,
	"keterangan_ppmse" varchar,
	"kota_kab" varchar,
	"marketplace" varchar,
	"metode_bayar" varchar,
	"nama_klpd" varchar,
	"nama_merchant" varchar,
	"nama_pemesan" varchar,
	"nama_satker" varchar,
	"order_desc" varchar,
	"order_id" varchar PRIMARY KEY NOT NULL,
	"provinsi" varchar,
	"status_konfirmasi_ppmse" varchar,
	"status_verif" varchar,
	"sumber_data" varchar,
	"tanggal_transaksi" timestamp,
	"valuasi" numeric
);
--> statement-breakpoint
CREATE TABLE "rup_master_satker_tahun" (
	"tahun" integer PRIMARY KEY NOT NULL,
	"satker" integer[]
);
--> statement-breakpoint
CREATE TABLE "paket_nontender_selesai" (
	"hps" numeric,
	"jenis_klpd" varchar,
	"jenis_pengadaan" varchar,
	"kd_klpd" varchar,
	"kd_lpse" integer,
	"kd_nontender" numeric NOT NULL,
	"kd_penyedia" numeric,
	"kd_pkt_dce" numeric,
	"kd_rup" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"kontrak_pembayaran" varchar,
	"kualifikasi_paket" varchar,
	"mak" varchar,
	"mtd_pemilihan" varchar,
	"nama_klpd" varchar,
	"nama_lpse" varchar,
	"nama_paket" varchar,
	"nama_penyedia" varchar,
	"nama_satker" varchar,
	"nilai_kontrak" numeric,
	"nilai_negosiasi" numeric,
	"nilai_pdn_kontrak" numeric,
	"nilai_penawaran" numeric,
	"nilai_terkoreksi" numeric,
	"nilai_umk_kontrak" numeric,
	"nip_nama_pokja" varchar,
	"nip_nama_pp" varchar,
	"nip_nama_ppk" varchar,
	"npwp_penyedia" varchar,
	"pagu" numeric,
	"status_nontender" varchar,
	"sumber_dana" varchar,
	"tahun_anggaran" integer,
	"tgl_pengumuman_nontender" timestamp,
	"tgl_selesai_nontender" timestamp,
	"url_lpse" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_paket_nontender_selesai'::regclass) NOT NULL,
	"_event_date" timestamp,
	"npwp16_penyedia" char(20),
	"lpse_id" numeric,
	"tgl_penarikan" timestamp
);
--> statement-breakpoint
CREATE TABLE "paket_purchase_old" (
	"no_paket" varchar NOT NULL,
	"nama_komoditas" varchar,
	"nama_paket" varchar,
	"rup_id" numeric,
	"nama_sumber_dana" varchar,
	"kode_anggaran" varchar,
	"jenis_instansi" varchar,
	"nama_instansi" varchar,
	"nama_satuan_kerja" varchar,
	"satuan_kerja_alamat" varchar,
	"satuan_kerja_npwp" varchar,
	"tanggal_buat_paket" timestamp,
	"tanggal_edit_paket" timestamp,
	"nama_pembuat_paket" varchar,
	"no_telp_pembuat_paket" varchar,
	"email_pembuat_paket" varchar,
	"nama_ppk" varchar,
	"jabatan_ppk" varchar,
	"ppk_nip" varchar,
	"nama_penyedia" varchar,
	"alamat_penyedia" varchar,
	"email_penyedia" varchar,
	"no_telp_penyedia" varchar,
	"nama_distributor" varchar,
	"alamat_distributor" varchar,
	"email_distributor" varchar,
	"no_telp_distributor" varchar,
	"jml_jenis_produk" numeric,
	"total" numeric,
	"npwp_penyedia" varchar,
	"npwp_distributor" varchar,
	"status_paket" varchar,
	"kd_satker" varchar,
	"tahun_anggaran" integer,
	"jenis_katalog" varchar,
	"nama_kategori" varchar,
	"nama_manufaktur" varchar,
	"nama_produk" varchar NOT NULL,
	"jenis_produk" varchar,
	"kuantitas" numeric,
	"harga_satuan" numeric,
	"ongkos_kirim" numeric,
	"total_harga" numeric,
	"deskripsi" varchar,
	"paket_status_str" varchar,
	"catatan_produk" varchar,
	"tkdn_produk" varchar,
	"penyedia_ukm" varchar,
	"kd_provinsi_wilayah_harga" integer,
	"kd_kabupaten_wilayah_harga" integer,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_paket_purchase_old'::regclass) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bast_nontender" (
	"kd_nontender" numeric NOT NULL,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"nama_klpd" varchar,
	"jenis_klpd" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"nama_satker" varchar,
	"alamat_satker" varchar,
	"kd_lpse" integer,
	"nama_paket" varchar,
	"mtd_pengadaan" varchar,
	"lingkup_pekerjaan" varchar,
	"no_sppbj" varchar,
	"no_kontrak" varchar,
	"tgl_kontrak" timestamp,
	"nilai_kontrak" numeric,
	"nip_ppk" varchar,
	"nama_ppk" varchar,
	"jabatan_ppk" varchar,
	"no_sk_ppk" varchar,
	"jabatan_penandatangan_sk" varchar,
	"nama_penyedia" varchar,
	"alamat_penyedia" varchar,
	"npwp_penyedia" varchar,
	"wakil_sah_penyedia" varchar,
	"jabatan_wakil_penyedia" varchar,
	"no_bast" varchar,
	"tgl_bast" timestamp,
	"no_bap" varchar,
	"tgl_bap" timestamp,
	"besar_pembayaran" numeric,
	"progres_pekerjaan" varchar,
	"cara_pembayaran_kontrak" varchar,
	"status_kontrak" varchar,
	"tgl_penetapan_status_kontrak" timestamp,
	"alasan_penetapan_status_kontrak" varchar,
	"apakah_addendum" varchar,
	"versi_addendum" integer,
	"alasan_addendum" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_bast_nontender'::regclass) NOT NULL,
	"npwp_16_penyedia" varchar(20),
	"_event_date" timestamp,
	"_inserted_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "isb_api" (
	"id" integer PRIMARY KEY DEFAULT 0 NOT NULL,
	"api_kelompok" varchar(255) DEFAULT '' NOT NULL,
	"api_layanan" varchar(255) DEFAULT '' NOT NULL,
	"api_keterangan" varchar(255),
	"is_active" boolean DEFAULT true NOT NULL,
	"api_url" varchar DEFAULT '' NOT NULL,
	"api_param" varchar DEFAULT '' NOT NULL,
	"api_lastupdate" timestamp
);
--> statement-breakpoint
CREATE TABLE "rup_master_komponen" (
	"is_deleted" boolean,
	"jenis_klpd" varchar,
	"kd_kegiatan" numeric,
	"kd_klpd" varchar,
	"kd_komponen" numeric PRIMARY KEY NOT NULL,
	"kd_komponen_lokal" varchar,
	"kd_komponen_str" varchar,
	"kd_kro" varchar,
	"kd_program" numeric,
	"kd_ro" varchar,
	"kd_satker" integer,
	"nama_klpd" varchar,
	"nama_komponen" varchar,
	"pagu_komponen" numeric,
	"tahun_anggaran" integer
);
--> statement-breakpoint
CREATE TABLE "rup_master_kegiatan" (
	"is_deleted" boolean,
	"jenis_klpd" varchar,
	"kd_kegiatan" numeric PRIMARY KEY NOT NULL,
	"kd_kegiatan_lokal" varchar,
	"kd_kegiatan_str" varchar,
	"kd_klpd" varchar,
	"kd_program" numeric,
	"kd_satker" numeric,
	"nama_kegiatan" varchar,
	"nama_klpd" varchar,
	"pagu_kegiatan" numeric,
	"tahun_anggaran" integer
);
--> statement-breakpoint
CREATE TABLE "rup_master_provinsi" (
	"kd_provinsi" numeric PRIMARY KEY NOT NULL,
	"nama_provinsi" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rup_master_kabupaten" (
	"kd_kabkota" numeric PRIMARY KEY NOT NULL,
	"kd_provinsi" numeric NOT NULL,
	"nama_kabkota" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rup_master_subkegiatan" (
	"is_deleted" boolean,
	"jenis_klpd" varchar,
	"kd_kegiatan" numeric,
	"kd_klpd" varchar,
	"kd_program" numeric,
	"kd_satker" numeric,
	"kd_subkegiatan" numeric PRIMARY KEY NOT NULL,
	"kd_subkegiatan_lokal" varchar,
	"kd_subkegiatan_str" varchar,
	"nama_klpd" varchar,
	"nama_subkegiatan" varchar,
	"pagu_subkegiatan" numeric,
	"tahun_anggaran" integer
);
--> statement-breakpoint
CREATE TABLE "rup_master_kro" (
	"is_deleted" boolean,
	"jenis_klpd" varchar,
	"kd_kegiatan" varchar,
	"kd_klpd" varchar,
	"kd_kro" varchar PRIMARY KEY NOT NULL,
	"kd_kro_lokal" varchar,
	"kd_kro_str" varchar,
	"kd_program" varchar,
	"kd_satker" integer,
	"nama_klpd" varchar,
	"nama_kro" varchar,
	"pagu_kro" numeric,
	"tahun_anggaran" integer
);
--> statement-breakpoint
CREATE TABLE "rup_struktur_anggaran_pd" (
	"belanja_btt" bigint,
	"belanja_modal" bigint,
	"belanja_non_pengadaan" bigint,
	"belanja_operasi" bigint,
	"belanja_pengadaan" bigint,
	"kd_klpd" varchar NOT NULL,
	"kd_satker" integer NOT NULL,
	"kd_satker_str" varchar,
	"nama_klpd" varchar,
	"nama_satker" varchar,
	"tahun_anggaran" integer,
	"total_belanja" bigint,
	"id" serial PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rup_master_ro" (
	"is_deleted" boolean,
	"jenis_klpd" varchar,
	"kd_kegiatan" varchar,
	"kd_klpd" varchar,
	"kd_kro" varchar,
	"kd_program" varchar,
	"kd_ro" varchar PRIMARY KEY NOT NULL,
	"kd_ro_lokal" varchar,
	"kd_ro_str" varchar,
	"kd_satker" integer,
	"nama_klpd" varchar,
	"nama_ro" varchar,
	"pagu_ro" numeric,
	"tahun_anggaran" integer
);
--> statement-breakpoint
CREATE TABLE "rup_master_subkomponen" (
	"is_deleted" boolean,
	"jenis_klpd" varchar,
	"kd_kegiatan" varchar,
	"kd_klpd" varchar,
	"kd_komponen" varchar,
	"kd_kro" varchar,
	"kd_program" varchar,
	"kd_ro" varchar,
	"kd_satker" integer,
	"kd_subkomponen" varchar PRIMARY KEY NOT NULL,
	"kd_subkomponen_lokal" varchar,
	"kd_subkomponen_str" varchar,
	"nama_klpd" varchar,
	"nama_subkomponen" varchar,
	"pagu_subkomponen" numeric,
	"tahun_anggaran" integer
);
--> statement-breakpoint
CREATE TABLE "rup_paket_anggaran_swakelola" (
	"asal_dana_klpd" varchar,
	"asal_dana_satker" varchar,
	"jenis_klpd" varchar,
	"kd_kegiatan" varchar,
	"kd_klpd" varchar,
	"kd_komponen" numeric,
	"kd_rup" varchar NOT NULL,
	"kd_rup_lokal" varchar,
	"kd_satker" numeric,
	"kd_satker_str" varchar,
	"kd_subkegiatan" varchar,
	"mak" varchar,
	"nama_klpd" varchar,
	"nama_satker" varchar,
	"pagu" numeric,
	"status_aktif_rup" varchar,
	"status_delete_rup" varchar,
	"status_umumkan_rup" varchar,
	"sumber_dana" varchar,
	"tahun_anggaran" integer NOT NULL,
	"tahun_anggaran_dana" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_rup_paket_anggaran_swakelola'::regclass) NOT NULL,
	"asal_dana" varchar,
	"_event_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "rup_master_program" (
	"is_deleted" boolean,
	"jenis_klpd" varchar,
	"kd_klpd" varchar,
	"kd_program" numeric PRIMARY KEY NOT NULL,
	"kd_program_lokal" numeric,
	"kd_program_str" varchar,
	"kd_satker" integer,
	"nama_klpd" varchar,
	"nama_program" varchar,
	"pagu_program" numeric,
	"tahun_anggaran" integer
);
--> statement-breakpoint
CREATE TABLE "paket_tender" (
	"hps" numeric,
	"jenis_klpd" varchar,
	"jenis_pengadaan" varchar,
	"kd_klpd" varchar,
	"kd_lpse" smallint,
	"kd_pkt_dce" bigint,
	"kd_rup" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"kd_tender" bigint PRIMARY KEY NOT NULL,
	"ket_ditutup" varchar,
	"ket_diulang" varchar,
	"kontrak_pembayaran" varchar,
	"kualifikasi_paket" varchar,
	"lokasi_pekerjaan" text,
	"mtd_evaluasi" varchar,
	"mtd_kualifikasi" varchar,
	"mtd_pemilihan" varchar,
	"nama_klpd" varchar,
	"nama_lpse" varchar,
	"nama_paket" varchar NOT NULL,
	"nama_pokja" varchar,
	"nama_ppk" varchar,
	"nama_satker" varchar,
	"nip_pokja" varchar,
	"nip_ppk" varchar,
	"pagu" numeric,
	"status_tender" varchar,
	"sumber_dana" varchar,
	"tahun_anggaran" integer,
	"tanggal_status" timestamp,
	"tgl_buat_paket" timestamp,
	"tgl_kolektif_kolegial" timestamp,
	"tgl_pengumuman_tender" timestamp,
	"url_lpse" varchar,
	"versi_tender" varchar,
	"list_tahun_anggaran" varchar(250),
	"max_lls_auditupdate" timestamp,
	"_event_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "paket_tender_selesai" (
	"hps" numeric,
	"jenis_klpd" varchar,
	"kd_klpd" varchar,
	"kd_lpse" smallint,
	"kd_paket" bigint,
	"kd_penyedia" numeric,
	"kd_rup_paket" varchar,
	"kd_satker" varchar,
	"kd_tender" bigint NOT NULL,
	"nama_klpd" varchar,
	"nama_penyedia" varchar,
	"nama_satker" varchar,
	"nilai_kontrak" numeric,
	"nilai_negosiasi" numeric,
	"nilai_pdn_kontrak" numeric,
	"nilai_penawaran" numeric,
	"nilai_terkoreksi" numeric,
	"nilai_umk_kontrak" numeric,
	"npwp_penyedia" varchar,
	"pagu" numeric,
	"tahun_anggaran" integer,
	"tgl_penetapan_pemenang" timestamp,
	"tgl_pengumuman_tender" timestamp,
	"id" serial PRIMARY KEY NOT NULL,
	"_event_date" timestamp,
	"npwp_16_penyedia" char(20)
);
--> statement-breakpoint
CREATE TABLE "paket_nontender" (
	"hps" numeric,
	"jenis_klpd" varchar,
	"jenis_pengadaan" varchar,
	"kd_klpd" varchar,
	"kd_lpse" bigint,
	"kd_nontender" bigint PRIMARY KEY NOT NULL,
	"kd_pkt_dce" bigint,
	"kd_rup" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"ket_ditutup" varchar,
	"ket_diulang" varchar,
	"kontrak_pembayaran" varchar,
	"kualifikasi_paket" varchar,
	"lokasi_pekerjaan" varchar,
	"mak" varchar,
	"mtd_pemilihan" varchar,
	"nama_klpd" varchar,
	"nama_lpse" varchar,
	"nama_paket" varchar,
	"nama_satker" varchar,
	"nip_nama_pokja" varchar,
	"nip_nama_pp" varchar,
	"nip_nama_ppk" varchar,
	"pagu" numeric,
	"status_nontender" varchar,
	"sumber_dana" varchar,
	"tahun_anggaran" integer,
	"tgl_buat_paket" timestamp,
	"tgl_kolektif_kolegial" timestamp,
	"tgl_pengumuman_nontender" timestamp,
	"url_lpse" varchar,
	"versi_nontender" varchar,
	"repeat_order" varchar,
	"lls_id" numeric
);
--> statement-breakpoint
CREATE TABLE "kontrak" (
	"kd_tender" numeric NOT NULL,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"nama_klpd" varchar,
	"jenis_klpd" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"nama_satker" varchar,
	"alamat_satker" varchar,
	"kd_lpse" integer,
	"nama_paket" varchar,
	"lingkup_pekerjaan" varchar,
	"no_sppbj" varchar,
	"no_kontrak" varchar NOT NULL,
	"tgl_kontrak" timestamp,
	"tgl_kontrak_awal" timestamp,
	"tgl_kontrak_akhir" timestamp,
	"kota_kontrak" varchar,
	"nip_ppk" varchar,
	"nama_ppk" varchar,
	"jabatan_ppk" varchar,
	"no_sk_ppk" varchar,
	"kd_penyedia" numeric NOT NULL,
	"nama_penyedia" varchar,
	"npwp_penyedia" varchar,
	"bentuk_usaha_penyedia" varchar,
	"tipe_penyedia" varchar,
	"anggota_kso" varchar,
	"wakil_sah_penyedia" varchar,
	"jabatan_wakil_penyedia" varchar,
	"nama_rek_bank" varchar,
	"no_rek_bank" varchar,
	"nama_pemilik_rek_bank" varchar,
	"nilai_kontrak" numeric,
	"alasan_ubah_nilai_kontrak" varchar,
	"alasan_nilai_kontrak_10_persen" varchar,
	"nilai_pdn_kontrak" numeric,
	"nilai_umk_kontrak" numeric,
	"jenis_kontrak" varchar,
	"informasi_lainnya" varchar,
	"status_kontrak" varchar,
	"tgl_penetapan_status_kontrak" timestamp,
	"alasan_penetapan_status_kontrak" varchar,
	"apakah_addendum" varchar,
	"versi_addendum" integer,
	"alasan_addendum" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_kontrak'::regclass) NOT NULL,
	"npwp_16_penyedia" varchar(20)
);
--> statement-breakpoint
CREATE TABLE "rup_master_satker" (
	"kd_satker" numeric PRIMARY KEY NOT NULL,
	"alamat" varchar(200),
	"fax" varchar(50),
	"jenis_klpd" varchar(50),
	"jenis_satker" varchar(50),
	"kd_klpd" varchar(20),
	"kd_satker_str" varchar(50),
	"ket_satker" text,
	"kode_eselon" varchar(50),
	"kodepos" varchar(10),
	"nama_klpd" varchar(200),
	"nama_satker" varchar(200),
	"status_satker" text,
	"telepon" varchar(20)
);
--> statement-breakpoint
CREATE TABLE "rup_paket_anggaran" (
	"asal_dana_klpd" varchar,
	"asal_dana_satker" varchar,
	"jenis_klpd" varchar,
	"kd_kegiatan" varchar,
	"kd_klpd" varchar,
	"kd_komponen" varchar,
	"kd_rup" varchar NOT NULL,
	"kd_rup_lokal" varchar,
	"kd_satker" numeric NOT NULL,
	"kd_satker_str" varchar,
	"kd_subkegiatan" varchar,
	"mak" varchar,
	"nama_klpd" varchar,
	"nama_satker" varchar,
	"pagu" numeric,
	"status_aktif_rup" varchar,
	"status_delete_rup" varchar,
	"status_umumkan_rup" varchar,
	"sumber_dana" varchar,
	"tahun_anggaran" integer,
	"tahun_anggaran_dana" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_rup_paket_anggaran'::regclass) NOT NULL,
	"asal_dana" varchar,
	"_event_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "rup_paket_lokasi" (
	"detail_lokasi" varchar,
	"jenis_klpd" varchar,
	"kab_kota" varchar,
	"kd_kab_kota" integer,
	"kd_klpd" varchar,
	"kd_provinsi" integer,
	"kd_rup" numeric NOT NULL,
	"kd_satker" integer NOT NULL,
	"kd_satker_str" varchar,
	"nama_klpd" varchar,
	"nama_satker" varchar,
	"provinsi" varchar,
	"tahun_anggaran" integer NOT NULL,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_rup_paket_lokasi'::regclass) NOT NULL,
	"_event_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "pencatatan" (
	"kd_nontender_pct" numeric PRIMARY KEY NOT NULL,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"nama_klpd" varchar,
	"jenis_klpd" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"nama_satker" varchar,
	"kd_lpse" integer,
	"kd_pkt_dce" numeric,
	"kd_rup" varchar,
	"nama_paket" varchar,
	"pagu" numeric,
	"total_realisasi" numeric,
	"nilai_pdn_pct" numeric,
	"nilai_umk_pct" numeric,
	"sumber_dana" varchar,
	"uraian_pekerjaan" varchar,
	"informasi_lainnya" varchar,
	"kategori_pengadaan" varchar,
	"mtd_pemilihan" varchar,
	"bukti_pembayaran" varchar,
	"status_nontender_pct" varchar,
	"status_nontender_pct_ket" varchar,
	"alasan_pembatalan" varchar,
	"nip_ppk" varchar,
	"nama_ppk" varchar,
	"tgl_buat_paket" timestamp,
	"tgl_mulai_paket" timestamp,
	"tgl_selesai_paket" timestamp,
	"_event_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "rup_paket_swakelola" (
	"jenis_klpd" varchar,
	"kd_klpd" varchar,
	"kd_klpd_penyelenggara" varchar,
	"kd_rup" numeric PRIMARY KEY NOT NULL,
	"kd_rup_lokal" varchar,
	"kd_satker" numeric,
	"kd_satker_str" varchar,
	"nama_klpd" varchar,
	"nama_klpd_penyelenggara" varchar,
	"nama_paket" varchar,
	"nama_ppk" varchar,
	"nama_satker" varchar,
	"nama_satker_penyelenggara" varchar,
	"nip_ppk" varchar,
	"pagu" numeric,
	"status_aktif_rup" varchar,
	"status_delete_rup" varchar,
	"status_umumkan_rup" varchar,
	"tahun_anggaran" integer,
	"tgl_akhir_pelaksanaan_kontrak" timestamp,
	"tgl_awal_pelaksanaan_kontrak" timestamp,
	"tgl_buat_paket" date,
	"tgl_pengumuman_paket" timestamp,
	"tipe_swakelola" varchar,
	"uraian_pekerjaan" varchar,
	"username_ppk" varchar,
	"volume_pekerjaan" varchar,
	"_event_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "rup_paket_swakelola_lokasi" (
	"detail_lokasi" varchar,
	"jenis_klpd" varchar,
	"kab_kota" varchar,
	"kd_kab_kota" varchar,
	"kd_klpd" varchar,
	"kd_provinsi" varchar,
	"kd_rup" varchar,
	"kd_satker" integer,
	"kd_satker_str" varchar,
	"nama_klpd" varchar,
	"nama_satker" varchar,
	"provinsi" varchar,
	"tahun_anggaran" integer,
	"_event_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "bast" (
	"kd_tender" numeric NOT NULL,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"nama_klpd" varchar,
	"jenis_klpd" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"nama_satker" varchar,
	"alamat_satker" varchar,
	"kd_lpse" integer,
	"nama_paket" varchar,
	"no_sppbj" varchar,
	"no_kontrak" varchar,
	"tgl_kontrak" timestamp,
	"nilai_kontrak" numeric,
	"nama_ppk" varchar,
	"nip_ppk" varchar,
	"jabatan_ppk" varchar,
	"no_sk_ppk" varchar,
	"jabatan_penandatangan_sk" varchar,
	"nama_penyedia" varchar,
	"alamat_penyedia" varchar,
	"npwp_penyedia" varchar,
	"wakil_sah_penyedia" varchar,
	"jabatan_wakil_penyedia" varchar,
	"no_bast" varchar,
	"tgl_bast" timestamp,
	"no_bap" varchar,
	"tgl_bap" timestamp,
	"besar_pembayaran" numeric,
	"progres_pekerjaan" integer,
	"cara_pembayaran_kontrak" varchar,
	"status_kontrak" varchar,
	"tgl_penetapan_status_kontrak" timestamp,
	"alasan_penetapan_status_kontrak" varchar,
	"apakah_addendum" varchar,
	"versi_addendum" integer,
	"alasan_addendum" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_bast'::regclass) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kontrak_nontender" (
	"kd_nontender" numeric NOT NULL,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"nama_klpd" varchar,
	"jenis_klpd" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"nama_satker" varchar,
	"alamat_satker" varchar,
	"kd_lpse" integer,
	"nama_paket" varchar,
	"mtd_pengadaan" varchar,
	"lingkup_pekerjaan" varchar,
	"no_sppbj" varchar,
	"no_kontrak" varchar,
	"tgl_kontrak" timestamp,
	"tgl_kontrak_awal" timestamp,
	"tgl_kontrak_akhir" timestamp,
	"kota_kontrak" varchar,
	"nip_ppk" varchar,
	"nama_ppk" varchar,
	"jabatan_ppk" varchar,
	"no_sk_ppk" varchar,
	"nama_penyedia" varchar,
	"npwp_penyedia" varchar,
	"bentuk_usaha_penyedia" varchar,
	"tipe_penyedia" varchar,
	"anggota_kso" varchar,
	"wakil_sah_penyedia" varchar,
	"jabatan_wakil_penyedia" varchar,
	"nama_rek_bank" varchar,
	"no_rek_bank" varchar,
	"nama_pemilik_rek_bank" varchar,
	"nilai_kontrak" numeric,
	"alasan_ubah_nilai_kontrak" varchar,
	"alasan_nilai_kontrak_10_persen" varchar,
	"nilai_pdn_kontrak" numeric,
	"nilai_umk_kontrak" numeric,
	"jenis_kontrak" varchar,
	"informasi_lainnya" varchar,
	"status_kontrak" varchar,
	"tgl_penetapan_status_kontrak" timestamp,
	"alasan_penetapan_status_kontrak" varchar,
	"apakah_addendum" varchar,
	"versi_addendum" integer,
	"alasan_addendum" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_kontrak_nontender'::regclass) NOT NULL,
	"npwp16_penyedia" varchar(20)
);
--> statement-breakpoint
CREATE TABLE "rup_paket" (
	"alasan_non_ukm" varchar,
	"jenis_klpd" varchar,
	"jenis_pengadaan" varchar,
	"kd_jenis_pengadaan" varchar,
	"kd_klpd" varchar,
	"kd_metode_pengadaan" varchar,
	"kd_rup" numeric PRIMARY KEY NOT NULL,
	"kd_rup_lokal" varchar,
	"kd_rup_swakelola" varchar,
	"kd_satker" numeric,
	"kd_satker_str" varchar,
	"metode_pengadaan" varchar,
	"nama_klpd" varchar,
	"nama_paket" varchar,
	"nama_ppk" varchar,
	"nama_satker" varchar,
	"nip_ppk" varchar,
	"pagu" numeric,
	"spesifikasi_pekerjaan" varchar,
	"status_aktif_rup" boolean,
	"status_delete_rup" boolean,
	"status_konsolidasi" varchar,
	"status_pdn" varchar,
	"status_pradipa" varchar,
	"status_ukm" varchar,
	"status_umumkan_rup" varchar,
	"tahun_anggaran" integer,
	"tgl_akhir_kontrak" date,
	"tgl_akhir_pemanfaatan" date,
	"tgl_akhir_pemilihan" date,
	"tgl_awal_kontrak" date,
	"tgl_awal_pemanfaatan" date,
	"tgl_awal_pemilihan" date,
	"tgl_buat_paket" date,
	"tgl_pengumuman_paket" timestamp,
	"tipe_paket" varchar,
	"urarian_pekerjaan" varchar,
	"username_ppk" varchar,
	"volume_pekerjaan" varchar,
	"status_dikecualikan" varchar,
	"alasan_dikecualikan" varchar,
	"tahun_pertama" integer,
	"kd_rup_tahun_pertama" numeric,
	"nomor_kontrak" varchar,
	"spp_aspek_ekonomi" boolean,
	"spp_aspek_sosial" boolean,
	"spp_aspek_lingkungan" boolean,
	"kode_rup_tahun_pertama" numeric,
	"_event_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "rup_master_instansi" (
	"id" varchar PRIMARY KEY NOT NULL,
	"nama" varchar NOT NULL,
	"prop_id" numeric,
	"kabupaten_id" numeric,
	"alamat" varchar,
	"jenis" varchar
);
--> statement-breakpoint
CREATE TABLE "swakelola_realisasi" (
	"kd_swakelola_pct" numeric NOT NULL,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"kd_satker" varchar,
	"kd_lpse" integer,
	"jenis_realisasi" varchar,
	"no_realisasi" varchar,
	"tgl_realisasi" timestamp,
	"nilai_realisasi" numeric,
	"dok_realisasi" varchar,
	"ket_realisasi" varchar,
	"nama_pelaksana" varchar,
	"npwp_pelaksana" varchar,
	"nip_ppk" varchar,
	"nama_ppk" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_swakelola_realisasi'::regclass) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "swakelola" (
	"kd_swakelola_pct" numeric PRIMARY KEY NOT NULL,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"nama_klpd" varchar,
	"jenis_klpd" varchar,
	"kd_satker" varchar,
	"kd_satker_str" varchar,
	"nama_satker" varchar,
	"kd_lpse" integer,
	"kd_pkt_dce" numeric,
	"kd_rup" varchar,
	"nama_paket" varchar,
	"pagu" numeric,
	"total_realisasi" numeric,
	"nilai_pdn_pct" numeric,
	"nilai_umk_pct" numeric,
	"sumber_dana" varchar,
	"uraian_pekerjaan" varchar,
	"informasi_lainnya" varchar,
	"tipe_swakelola" varchar,
	"tipe_swakelola_nama" varchar,
	"status_swakelola_pct" varchar,
	"status_swakelola_pct_ket" varchar,
	"alasan_pembatalan" varchar,
	"nip_ppk" varchar,
	"nama_ppk" varchar,
	"tgl_buat_paket" timestamp,
	"tgl_mulai_paket" timestamp,
	"tgl_selesai_paket" timestamp
);
--> statement-breakpoint
CREATE TABLE "pencatatan_realisasi" (
	"kd_nontender_pct" numeric NOT NULL,
	"tahun_anggaran" integer,
	"kd_klpd" varchar,
	"kd_satker" varchar,
	"kd_lpse" integer,
	"kategori_pengadaan" varchar,
	"mtd_pemilihan" varchar,
	"jenis_realisasi" varchar,
	"no_realisasi" varchar,
	"tgl_realisasi" timestamp,
	"nilai_realisasi" numeric,
	"dok_realisasi" varchar,
	"ket_realisasi" varchar,
	"nama_penyedia" varchar,
	"npwp_penyedia" varchar,
	"nip_ppk" varchar,
	"nama_ppk" varchar,
	"id" numeric PRIMARY KEY DEFAULT nextval('seq_pencatatan_realisasi'::regclass) NOT NULL,
	"jenis_penyedia" varchar,
	"nama_klpd" varchar,
	"jenis_klpd" varchar,
	"_event_date" timestamp,
	"kd_satker_str" varchar,
	"nama_satker" varchar,
	"nama_lpse" varchar,
	"kd_paket_dce" numeric,
	"kd_rup_paket" numeric,
	"nama_paket" varchar,
	"pagu" varchar
);
--> statement-breakpoint
CREATE TABLE "scheduled_tasks" (
	"task_name" text NOT NULL,
	"task_instance" text NOT NULL,
	"task_data" "bytea",
	"execution_time" timestamp with time zone NOT NULL,
	"picked" boolean NOT NULL,
	"picked_by" text,
	"last_success" timestamp with time zone,
	"last_failure" timestamp with time zone,
	"consecutive_failures" integer,
	"last_heartbeat" timestamp with time zone,
	"version" bigint NOT NULL,
	CONSTRAINT "scheduled_tasks_pkey" PRIMARY KEY("task_name","task_instance")
);
--> statement-breakpoint
CREATE TABLE "rup_struktur_anggaran_kl" (
	"belanja_barjas" bigint,
	"belanja_modal" bigint,
	"belanja_nonpengadaan_hibah" bigint,
	"belanja_nonpengadaan_lainnya" bigint,
	"belanja_nonpengadaan_sosial" bigint,
	"belanja_pegawai" bigint,
	"belanja_pengadaan_hibah" bigint,
	"belanja_pengadaan_lainnya" bigint,
	"belanja_pengadaan_sosial" bigint,
	"kd_klpd" varchar NOT NULL,
	"kd_satker" numeric NOT NULL,
	"kd_satker_str" varchar,
	"nama_klpd" varchar,
	"nama_satker" varchar,
	"tahun_anggaran" integer NOT NULL,
	"total_belanja" bigint,
	"total_belanja_hibah" bigint,
	"total_belanja_lainnya" bigint,
	"total_belanja_sosial" bigint,
	CONSTRAINT "rup_struktur_anggaran_kl_pkey" PRIMARY KEY("kd_klpd","kd_satker","tahun_anggaran")
);
--> statement-breakpoint
ALTER TABLE "rup_master_kabupaten" ADD CONSTRAINT "fk_kab_propinsi" FOREIGN KEY ("kd_provinsi") REFERENCES "public"."rup_master_provinsi"("kd_provinsi") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "spse_nontender_pengumuman_tahun" ON "paket_nontender" USING btree ("tahun_anggaran" int4_ops);--> statement-breakpoint
CREATE INDEX "rup_paket_swakelola_terumumkan_tahun" ON "rup_paket_swakelola" USING btree ("tahun_anggaran" int4_ops);--> statement-breakpoint
CREATE INDEX "rup_paket_penyedia_terumumkan_tahun" ON "rup_paket" USING btree ("tahun_anggaran" int4_ops);--> statement-breakpoint
CREATE INDEX "execution_time_idx" ON "scheduled_tasks" USING btree ("execution_time" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "last_heartbeat_idx" ON "scheduled_tasks" USING btree ("last_heartbeat" timestamptz_ops);
*/