import { pgTable, numeric, varchar, integer, timestamp, char, boolean, foreignKey, bigint, serial, smallint, text, index, date, primaryKey, pgSequence } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"


export const seqPaketTenderSelesai = pgSequence("seq_paket_tender_selesai", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqPaketNontenderSelesai = pgSequence("seq_paket_nontender_selesai", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqKontrak = pgSequence("seq_kontrak", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqRupPaketAnggaran = pgSequence("seq_rup_paket_anggaran", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqPencatatanRealisasi = pgSequence("seq_pencatatan_realisasi", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqPaketPurchaseOld = pgSequence("seq_paket_purchase_old", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqKontrakNontender = pgSequence("seq_kontrak_nontender", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqBastNontender = pgSequence("seq_bast_nontender", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqBast = pgSequence("seq_bast", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqSwakelolaRealisasi = pgSequence("seq_swakelola_realisasi", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqRupPaketLokasi = pgSequence("seq_rup_paket_lokasi", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqRupPaketAnggaranSwakelola = pgSequence("seq_rup_paket_anggaran_swakelola", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const seqPaketPurchase = pgSequence("seq_paket_purchase", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })

export const paketPurchase = pgTable("paket_purchase", {
	kdPaket: numeric("kd_paket").notNull(),
	noPaket: varchar("no_paket"),
	namaPaket: varchar("nama_paket"),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	satkerId: numeric("satker_id"),
	namaSatker: varchar("nama_satker"),
	alamatSatker: varchar("alamat_satker"),
	npwpSatker: varchar("npwp_satker"),
	kdRup: numeric("kd_rup"),
	namaSumberDana: varchar("nama_sumber_dana"),
	kodeAnggaran: varchar("kode_anggaran"),
	kdKomoditas: numeric("kd_komoditas"),
	kdProduk: numeric("kd_produk").notNull(),
	kdPenyedia: numeric("kd_penyedia"),
	kdPenyediaDistributor: numeric("kd_penyedia_distributor"),
	jmlJenisProduk: numeric("jml_jenis_produk"),
	kuantitas: numeric(),
	hargaSatuan: numeric("harga_satuan"),
	ongkosKirim: numeric("ongkos_kirim"),
	totalHarga: numeric("total_harga"),
	kdUserPokja: numeric("kd_user_pokja"),
	noTelpUserPokja: varchar("no_telp_user_pokja"),
	emailUserPokja: varchar("email_user_pokja"),
	kdUserPpk: numeric("kd_user_ppk"),
	ppkNip: varchar("ppk_nip"),
	jabatanPpk: varchar("jabatan_ppk"),
	tanggalBuatPaket: timestamp("tanggal_buat_paket", { mode: 'string' }),
	tanggalEditPaket: timestamp("tanggal_edit_paket", { mode: 'string' }),
	deskripsi: varchar(),
	statusPaket: varchar("status_paket"),
	paketStatusStr: varchar("paket_status_str"),
	catatanProduk: varchar("catatan_produk"),
	kdProvinsiWilayahHarga: integer("kd_provinsi_wilayah_harga"),
	kdKabupatenWilayahHarga: integer("kd_kabupaten_wilayah_harga"),
	id: numeric().default('nextval('seq_paket_purchase'::regclass)').primaryKey().notNull(),
});

export const tokodaringRealisasi = pgTable("tokodaring_realisasi", {
	jenisTransaksi: varchar("jenis_transaksi"),
	kategori: varchar(),
	kdKlpd: varchar("kd_klpd"),
	kdSatker: varchar("kd_satker"),
	keteranganPpmse: varchar("keterangan_ppmse"),
	kotaKab: varchar("kota_kab"),
	marketplace: varchar(),
	metodeBayar: varchar("metode_bayar"),
	namaKlpd: varchar("nama_klpd"),
	namaMerchant: varchar("nama_merchant"),
	namaPemesan: varchar("nama_pemesan"),
	namaSatker: varchar("nama_satker"),
	orderDesc: varchar("order_desc"),
	orderId: varchar("order_id").primaryKey().notNull(),
	provinsi: varchar(),
	statusKonfirmasiPpmse: varchar("status_konfirmasi_ppmse"),
	statusVerif: varchar("status_verif"),
	sumberData: varchar("sumber_data"),
	tanggalTransaksi: timestamp("tanggal_transaksi", { mode: 'string' }),
	valuasi: numeric(),
});

export const rupMasterSatkerTahun = pgTable("rup_master_satker_tahun", {
	tahun: integer().primaryKey().notNull(),
	satker: integer().array(),
});

export const paketNontenderSelesai = pgTable("paket_nontender_selesai", {
	hps: numeric(),
	jenisKlpd: varchar("jenis_klpd"),
	jenisPengadaan: varchar("jenis_pengadaan"),
	kdKlpd: varchar("kd_klpd"),
	kdLpse: integer("kd_lpse"),
	kdNontender: numeric("kd_nontender").notNull(),
	kdPenyedia: numeric("kd_penyedia"),
	kdPktDce: numeric("kd_pkt_dce"),
	kdRup: varchar("kd_rup"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	kontrakPembayaran: varchar("kontrak_pembayaran"),
	kualifikasiPaket: varchar("kualifikasi_paket"),
	mak: varchar(),
	mtdPemilihan: varchar("mtd_pemilihan"),
	namaKlpd: varchar("nama_klpd"),
	namaLpse: varchar("nama_lpse"),
	namaPaket: varchar("nama_paket"),
	namaPenyedia: varchar("nama_penyedia"),
	namaSatker: varchar("nama_satker"),
	nilaiKontrak: numeric("nilai_kontrak"),
	nilaiNegosiasi: numeric("nilai_negosiasi"),
	nilaiPdnKontrak: numeric("nilai_pdn_kontrak"),
	nilaiPenawaran: numeric("nilai_penawaran"),
	nilaiTerkoreksi: numeric("nilai_terkoreksi"),
	nilaiUmkKontrak: numeric("nilai_umk_kontrak"),
	nipNamaPokja: varchar("nip_nama_pokja"),
	nipNamaPp: varchar("nip_nama_pp"),
	nipNamaPpk: varchar("nip_nama_ppk"),
	npwpPenyedia: varchar("npwp_penyedia"),
	pagu: numeric(),
	statusNontender: varchar("status_nontender"),
	sumberDana: varchar("sumber_dana"),
	tahunAnggaran: integer("tahun_anggaran"),
	tglPengumumanNontender: timestamp("tgl_pengumuman_nontender", { mode: 'string' }),
	tglSelesaiNontender: timestamp("tgl_selesai_nontender", { mode: 'string' }),
	urlLpse: varchar("url_lpse"),
	id: numeric().default('nextval('seq_paket_nontender_selesai'::regclass)').primaryKey().notNull(),
	eventDate: timestamp("_event_date", { mode: 'string' }),
	npwp16Penyedia: char("npwp16_penyedia", { length: 20 }),
	lpseId: numeric("lpse_id"),
	tglPenarikan: timestamp("tgl_penarikan", { mode: 'string' }),
});

export const paketPurchaseOld = pgTable("paket_purchase_old", {
	noPaket: varchar("no_paket").notNull(),
	namaKomoditas: varchar("nama_komoditas"),
	namaPaket: varchar("nama_paket"),
	rupId: numeric("rup_id"),
	namaSumberDana: varchar("nama_sumber_dana"),
	kodeAnggaran: varchar("kode_anggaran"),
	jenisInstansi: varchar("jenis_instansi"),
	namaInstansi: varchar("nama_instansi"),
	namaSatuanKerja: varchar("nama_satuan_kerja"),
	satuanKerjaAlamat: varchar("satuan_kerja_alamat"),
	satuanKerjaNpwp: varchar("satuan_kerja_npwp"),
	tanggalBuatPaket: timestamp("tanggal_buat_paket", { mode: 'string' }),
	tanggalEditPaket: timestamp("tanggal_edit_paket", { mode: 'string' }),
	namaPembuatPaket: varchar("nama_pembuat_paket"),
	noTelpPembuatPaket: varchar("no_telp_pembuat_paket"),
	emailPembuatPaket: varchar("email_pembuat_paket"),
	namaPpk: varchar("nama_ppk"),
	jabatanPpk: varchar("jabatan_ppk"),
	ppkNip: varchar("ppk_nip"),
	namaPenyedia: varchar("nama_penyedia"),
	alamatPenyedia: varchar("alamat_penyedia"),
	emailPenyedia: varchar("email_penyedia"),
	noTelpPenyedia: varchar("no_telp_penyedia"),
	namaDistributor: varchar("nama_distributor"),
	alamatDistributor: varchar("alamat_distributor"),
	emailDistributor: varchar("email_distributor"),
	noTelpDistributor: varchar("no_telp_distributor"),
	jmlJenisProduk: numeric("jml_jenis_produk"),
	total: numeric(),
	npwpPenyedia: varchar("npwp_penyedia"),
	npwpDistributor: varchar("npwp_distributor"),
	statusPaket: varchar("status_paket"),
	kdSatker: varchar("kd_satker"),
	tahunAnggaran: integer("tahun_anggaran"),
	jenisKatalog: varchar("jenis_katalog"),
	namaKategori: varchar("nama_kategori"),
	namaManufaktur: varchar("nama_manufaktur"),
	namaProduk: varchar("nama_produk").notNull(),
	jenisProduk: varchar("jenis_produk"),
	kuantitas: numeric(),
	hargaSatuan: numeric("harga_satuan"),
	ongkosKirim: numeric("ongkos_kirim"),
	totalHarga: numeric("total_harga"),
	deskripsi: varchar(),
	paketStatusStr: varchar("paket_status_str"),
	catatanProduk: varchar("catatan_produk"),
	tkdnProduk: varchar("tkdn_produk"),
	penyediaUkm: varchar("penyedia_ukm"),
	kdProvinsiWilayahHarga: integer("kd_provinsi_wilayah_harga"),
	kdKabupatenWilayahHarga: integer("kd_kabupaten_wilayah_harga"),
	id: numeric().default('nextval('seq_paket_purchase_old'::regclass)').primaryKey().notNull(),
});

export const bastNontender = pgTable("bast_nontender", {
	kdNontender: numeric("kd_nontender").notNull(),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	namaKlpd: varchar("nama_klpd"),
	jenisKlpd: varchar("jenis_klpd"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	namaSatker: varchar("nama_satker"),
	alamatSatker: varchar("alamat_satker"),
	kdLpse: integer("kd_lpse"),
	namaPaket: varchar("nama_paket"),
	mtdPengadaan: varchar("mtd_pengadaan"),
	lingkupPekerjaan: varchar("lingkup_pekerjaan"),
	noSppbj: varchar("no_sppbj"),
	noKontrak: varchar("no_kontrak"),
	tglKontrak: timestamp("tgl_kontrak", { mode: 'string' }),
	nilaiKontrak: numeric("nilai_kontrak"),
	nipPpk: varchar("nip_ppk"),
	namaPpk: varchar("nama_ppk"),
	jabatanPpk: varchar("jabatan_ppk"),
	noSkPpk: varchar("no_sk_ppk"),
	jabatanPenandatanganSk: varchar("jabatan_penandatangan_sk"),
	namaPenyedia: varchar("nama_penyedia"),
	alamatPenyedia: varchar("alamat_penyedia"),
	npwpPenyedia: varchar("npwp_penyedia"),
	wakilSahPenyedia: varchar("wakil_sah_penyedia"),
	jabatanWakilPenyedia: varchar("jabatan_wakil_penyedia"),
	noBast: varchar("no_bast"),
	tglBast: timestamp("tgl_bast", { mode: 'string' }),
	noBap: varchar("no_bap"),
	tglBap: timestamp("tgl_bap", { mode: 'string' }),
	besarPembayaran: numeric("besar_pembayaran"),
	progresPekerjaan: varchar("progres_pekerjaan"),
	caraPembayaranKontrak: varchar("cara_pembayaran_kontrak"),
	statusKontrak: varchar("status_kontrak"),
	tglPenetapanStatusKontrak: timestamp("tgl_penetapan_status_kontrak", { mode: 'string' }),
	alasanPenetapanStatusKontrak: varchar("alasan_penetapan_status_kontrak"),
	apakahAddendum: varchar("apakah_addendum"),
	versiAddendum: integer("versi_addendum"),
	alasanAddendum: varchar("alasan_addendum"),
	id: numeric().default('nextval('seq_bast_nontender'::regclass)').primaryKey().notNull(),
	npwp16Penyedia: varchar("npwp_16_penyedia", { length: 20 }),
	eventDate: timestamp("_event_date", { mode: 'string' }),
	insertedDate: timestamp("_inserted_date", { mode: 'string' }),
});

export const isbApi = pgTable("isb_api", {
	id: integer().default(0).primaryKey().notNull(),
	apiKelompok: varchar("api_kelompok", { length: 255 }).default(').notNull(),
	apiLayanan: varchar("api_layanan", { length: 255 }).default(').notNull(),
	apiKeterangan: varchar("api_keterangan", { length: 255 }),
	isActive: boolean("is_active").default(true).notNull(),
	apiUrl: varchar("api_url").default(').notNull(),
	apiParam: varchar("api_param").default(').notNull(),
	apiLastupdate: timestamp("api_lastupdate", { mode: 'string' }),
});

export const rupMasterKomponen = pgTable("rup_master_komponen", {
	isDeleted: boolean("is_deleted"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKegiatan: numeric("kd_kegiatan"),
	kdKlpd: varchar("kd_klpd"),
	kdKomponen: numeric("kd_komponen").primaryKey().notNull(),
	kdKomponenLokal: varchar("kd_komponen_lokal"),
	kdKomponenStr: varchar("kd_komponen_str"),
	kdKro: varchar("kd_kro"),
	kdProgram: numeric("kd_program"),
	kdRo: varchar("kd_ro"),
	kdSatker: integer("kd_satker"),
	namaKlpd: varchar("nama_klpd"),
	namaKomponen: varchar("nama_komponen"),
	paguKomponen: numeric("pagu_komponen"),
	tahunAnggaran: integer("tahun_anggaran"),
});

export const rupMasterKegiatan = pgTable("rup_master_kegiatan", {
	isDeleted: boolean("is_deleted"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKegiatan: numeric("kd_kegiatan").primaryKey().notNull(),
	kdKegiatanLokal: varchar("kd_kegiatan_lokal"),
	kdKegiatanStr: varchar("kd_kegiatan_str"),
	kdKlpd: varchar("kd_klpd"),
	kdProgram: numeric("kd_program"),
	kdSatker: numeric("kd_satker"),
	namaKegiatan: varchar("nama_kegiatan"),
	namaKlpd: varchar("nama_klpd"),
	paguKegiatan: numeric("pagu_kegiatan"),
	tahunAnggaran: integer("tahun_anggaran"),
});

export const rupMasterProvinsi = pgTable("rup_master_provinsi", {
	kdProvinsi: numeric("kd_provinsi").primaryKey().notNull(),
	namaProvinsi: varchar("nama_provinsi", { length: 255 }).notNull(),
});

export const rupMasterKabupaten = pgTable("rup_master_kabupaten", {
	kdKabkota: numeric("kd_kabkota").primaryKey().notNull(),
	kdProvinsi: numeric("kd_provinsi").notNull(),
	namaKabkota: varchar("nama_kabkota", { length: 255 }).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.kdProvinsi],
			foreignColumns: [rupMasterProvinsi.kdProvinsi],
			name: "fk_kab_propinsi"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const rupMasterSubkegiatan = pgTable("rup_master_subkegiatan", {
	isDeleted: boolean("is_deleted"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKegiatan: numeric("kd_kegiatan"),
	kdKlpd: varchar("kd_klpd"),
	kdProgram: numeric("kd_program"),
	kdSatker: numeric("kd_satker"),
	kdSubkegiatan: numeric("kd_subkegiatan").primaryKey().notNull(),
	kdSubkegiatanLokal: varchar("kd_subkegiatan_lokal"),
	kdSubkegiatanStr: varchar("kd_subkegiatan_str"),
	namaKlpd: varchar("nama_klpd"),
	namaSubkegiatan: varchar("nama_subkegiatan"),
	paguSubkegiatan: numeric("pagu_subkegiatan"),
	tahunAnggaran: integer("tahun_anggaran"),
});

export const rupMasterKro = pgTable("rup_master_kro", {
	isDeleted: boolean("is_deleted"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKegiatan: varchar("kd_kegiatan"),
	kdKlpd: varchar("kd_klpd"),
	kdKro: varchar("kd_kro").primaryKey().notNull(),
	kdKroLokal: varchar("kd_kro_lokal"),
	kdKroStr: varchar("kd_kro_str"),
	kdProgram: varchar("kd_program"),
	kdSatker: integer("kd_satker"),
	namaKlpd: varchar("nama_klpd"),
	namaKro: varchar("nama_kro"),
	paguKro: numeric("pagu_kro"),
	tahunAnggaran: integer("tahun_anggaran"),
});

export const rupStrukturAnggaranPd = pgTable("rup_struktur_anggaran_pd", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaBtt: bigint("belanja_btt", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaModal: bigint("belanja_modal", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaNonPengadaan: bigint("belanja_non_pengadaan", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaOperasi: bigint("belanja_operasi", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaPengadaan: bigint("belanja_pengadaan", { mode: "number" }),
	kdKlpd: varchar("kd_klpd").notNull(),
	kdSatker: integer("kd_satker").notNull(),
	kdSatkerStr: varchar("kd_satker_str"),
	namaKlpd: varchar("nama_klpd"),
	namaSatker: varchar("nama_satker"),
	tahunAnggaran: integer("tahun_anggaran"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalBelanja: bigint("total_belanja", { mode: "number" }),
	id: serial().primaryKey().notNull(),
});

export const rupMasterRo = pgTable("rup_master_ro", {
	isDeleted: boolean("is_deleted"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKegiatan: varchar("kd_kegiatan"),
	kdKlpd: varchar("kd_klpd"),
	kdKro: varchar("kd_kro"),
	kdProgram: varchar("kd_program"),
	kdRo: varchar("kd_ro").primaryKey().notNull(),
	kdRoLokal: varchar("kd_ro_lokal"),
	kdRoStr: varchar("kd_ro_str"),
	kdSatker: integer("kd_satker"),
	namaKlpd: varchar("nama_klpd"),
	namaRo: varchar("nama_ro"),
	paguRo: numeric("pagu_ro"),
	tahunAnggaran: integer("tahun_anggaran"),
});

export const rupMasterSubkomponen = pgTable("rup_master_subkomponen", {
	isDeleted: boolean("is_deleted"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKegiatan: varchar("kd_kegiatan"),
	kdKlpd: varchar("kd_klpd"),
	kdKomponen: varchar("kd_komponen"),
	kdKro: varchar("kd_kro"),
	kdProgram: varchar("kd_program"),
	kdRo: varchar("kd_ro"),
	kdSatker: integer("kd_satker"),
	kdSubkomponen: varchar("kd_subkomponen").primaryKey().notNull(),
	kdSubkomponenLokal: varchar("kd_subkomponen_lokal"),
	kdSubkomponenStr: varchar("kd_subkomponen_str"),
	namaKlpd: varchar("nama_klpd"),
	namaSubkomponen: varchar("nama_subkomponen"),
	paguSubkomponen: numeric("pagu_subkomponen"),
	tahunAnggaran: integer("tahun_anggaran"),
});

export const rupPaketAnggaranSwakelola = pgTable("rup_paket_anggaran_swakelola", {
	asalDanaKlpd: varchar("asal_dana_klpd"),
	asalDanaSatker: varchar("asal_dana_satker"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKegiatan: varchar("kd_kegiatan"),
	kdKlpd: varchar("kd_klpd"),
	kdKomponen: numeric("kd_komponen"),
	kdRup: varchar("kd_rup").notNull(),
	kdRupLokal: varchar("kd_rup_lokal"),
	kdSatker: numeric("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	kdSubkegiatan: varchar("kd_subkegiatan"),
	mak: varchar(),
	namaKlpd: varchar("nama_klpd"),
	namaSatker: varchar("nama_satker"),
	pagu: numeric(),
	statusAktifRup: varchar("status_aktif_rup"),
	statusDeleteRup: varchar("status_delete_rup"),
	statusUmumkanRup: varchar("status_umumkan_rup"),
	sumberDana: varchar("sumber_dana"),
	tahunAnggaran: integer("tahun_anggaran").notNull(),
	tahunAnggaranDana: varchar("tahun_anggaran_dana"),
	id: numeric().default('nextval('seq_rup_paket_anggaran_swakelola'::regclass)').primaryKey().notNull(),
	asalDana: varchar("asal_dana"),
	eventDate: timestamp("_event_date", { mode: 'string' }),
});

export const rupMasterProgram = pgTable("rup_master_program", {
	isDeleted: boolean("is_deleted"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKlpd: varchar("kd_klpd"),
	kdProgram: numeric("kd_program").primaryKey().notNull(),
	kdProgramLokal: numeric("kd_program_lokal"),
	kdProgramStr: varchar("kd_program_str"),
	kdSatker: integer("kd_satker"),
	namaKlpd: varchar("nama_klpd"),
	namaProgram: varchar("nama_program"),
	paguProgram: numeric("pagu_program"),
	tahunAnggaran: integer("tahun_anggaran"),
});

export const paketTender = pgTable("paket_tender", {
	hps: numeric(),
	jenisKlpd: varchar("jenis_klpd"),
	jenisPengadaan: varchar("jenis_pengadaan"),
	kdKlpd: varchar("kd_klpd"),
	kdLpse: smallint("kd_lpse"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	kdPktDce: bigint("kd_pkt_dce", { mode: "number" }),
	kdRup: varchar("kd_rup"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	kdTender: bigint("kd_tender", { mode: "number" }).primaryKey().notNull(),
	ketDitutup: varchar("ket_ditutup"),
	ketDiulang: varchar("ket_diulang"),
	kontrakPembayaran: varchar("kontrak_pembayaran"),
	kualifikasiPaket: varchar("kualifikasi_paket"),
	lokasiPekerjaan: text("lokasi_pekerjaan"),
	mtdEvaluasi: varchar("mtd_evaluasi"),
	mtdKualifikasi: varchar("mtd_kualifikasi"),
	mtdPemilihan: varchar("mtd_pemilihan"),
	namaKlpd: varchar("nama_klpd"),
	namaLpse: varchar("nama_lpse"),
	namaPaket: varchar("nama_paket").notNull(),
	namaPokja: varchar("nama_pokja"),
	namaPpk: varchar("nama_ppk"),
	namaSatker: varchar("nama_satker"),
	nipPokja: varchar("nip_pokja"),
	nipPpk: varchar("nip_ppk"),
	pagu: numeric(),
	statusTender: varchar("status_tender"),
	sumberDana: varchar("sumber_dana"),
	tahunAnggaran: integer("tahun_anggaran"),
	tanggalStatus: timestamp("tanggal_status", { mode: 'string' }),
	tglBuatPaket: timestamp("tgl_buat_paket", { mode: 'string' }),
	tglKolektifKolegial: timestamp("tgl_kolektif_kolegial", { mode: 'string' }),
	tglPengumumanTender: timestamp("tgl_pengumuman_tender", { mode: 'string' }),
	urlLpse: varchar("url_lpse"),
	versiTender: varchar("versi_tender"),
	listTahunAnggaran: varchar("list_tahun_anggaran", { length: 250 }),
	maxLlsAuditupdate: timestamp("max_lls_auditupdate", { mode: 'string' }),
	eventDate: timestamp("_event_date", { mode: 'string' }),
});

export const paketTenderSelesai = pgTable("paket_tender_selesai", {
	hps: numeric(),
	jenisKlpd: varchar("jenis_klpd"),
	kdKlpd: varchar("kd_klpd"),
	kdLpse: smallint("kd_lpse"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	kdPaket: bigint("kd_paket", { mode: "number" }),
	kdPenyedia: numeric("kd_penyedia"),
	kdRupPaket: varchar("kd_rup_paket"),
	kdSatker: varchar("kd_satker"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	kdTender: bigint("kd_tender", { mode: "number" }).notNull(),
	namaKlpd: varchar("nama_klpd"),
	namaPenyedia: varchar("nama_penyedia"),
	namaSatker: varchar("nama_satker"),
	nilaiKontrak: numeric("nilai_kontrak"),
	nilaiNegosiasi: numeric("nilai_negosiasi"),
	nilaiPdnKontrak: numeric("nilai_pdn_kontrak"),
	nilaiPenawaran: numeric("nilai_penawaran"),
	nilaiTerkoreksi: numeric("nilai_terkoreksi"),
	nilaiUmkKontrak: numeric("nilai_umk_kontrak"),
	npwpPenyedia: varchar("npwp_penyedia"),
	pagu: numeric(),
	tahunAnggaran: integer("tahun_anggaran"),
	tglPenetapanPemenang: timestamp("tgl_penetapan_pemenang", { mode: 'string' }),
	tglPengumumanTender: timestamp("tgl_pengumuman_tender", { mode: 'string' }),
	id: serial().primaryKey().notNull(),
	eventDate: timestamp("_event_date", { mode: 'string' }),
	npwp16Penyedia: char("npwp_16_penyedia", { length: 20 }),
});

export const paketNontender = pgTable("paket_nontender", {
	hps: numeric(),
	jenisKlpd: varchar("jenis_klpd"),
	jenisPengadaan: varchar("jenis_pengadaan"),
	kdKlpd: varchar("kd_klpd"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	kdLpse: bigint("kd_lpse", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	kdNontender: bigint("kd_nontender", { mode: "number" }).primaryKey().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	kdPktDce: bigint("kd_pkt_dce", { mode: "number" }),
	kdRup: varchar("kd_rup"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	ketDitutup: varchar("ket_ditutup"),
	ketDiulang: varchar("ket_diulang"),
	kontrakPembayaran: varchar("kontrak_pembayaran"),
	kualifikasiPaket: varchar("kualifikasi_paket"),
	lokasiPekerjaan: varchar("lokasi_pekerjaan"),
	mak: varchar(),
	mtdPemilihan: varchar("mtd_pemilihan"),
	namaKlpd: varchar("nama_klpd"),
	namaLpse: varchar("nama_lpse"),
	namaPaket: varchar("nama_paket"),
	namaSatker: varchar("nama_satker"),
	nipNamaPokja: varchar("nip_nama_pokja"),
	nipNamaPp: varchar("nip_nama_pp"),
	nipNamaPpk: varchar("nip_nama_ppk"),
	pagu: numeric(),
	statusNontender: varchar("status_nontender"),
	sumberDana: varchar("sumber_dana"),
	tahunAnggaran: integer("tahun_anggaran"),
	tglBuatPaket: timestamp("tgl_buat_paket", { mode: 'string' }),
	tglKolektifKolegial: timestamp("tgl_kolektif_kolegial", { mode: 'string' }),
	tglPengumumanNontender: timestamp("tgl_pengumuman_nontender", { mode: 'string' }),
	urlLpse: varchar("url_lpse"),
	versiNontender: varchar("versi_nontender"),
	repeatOrder: varchar("repeat_order"),
	llsId: numeric("lls_id"),
}, (table) => [
	index("spse_nontender_pengumuman_tahun").using("btree", table.tahunAnggaran.asc().nullsLast().op("int4_ops")),
]);

export const kontrak = pgTable("kontrak", {
	kdTender: numeric("kd_tender").notNull(),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	namaKlpd: varchar("nama_klpd"),
	jenisKlpd: varchar("jenis_klpd"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	namaSatker: varchar("nama_satker"),
	alamatSatker: varchar("alamat_satker"),
	kdLpse: integer("kd_lpse"),
	namaPaket: varchar("nama_paket"),
	lingkupPekerjaan: varchar("lingkup_pekerjaan"),
	noSppbj: varchar("no_sppbj"),
	noKontrak: varchar("no_kontrak").notNull(),
	tglKontrak: timestamp("tgl_kontrak", { mode: 'string' }),
	tglKontrakAwal: timestamp("tgl_kontrak_awal", { mode: 'string' }),
	tglKontrakAkhir: timestamp("tgl_kontrak_akhir", { mode: 'string' }),
	kotaKontrak: varchar("kota_kontrak"),
	nipPpk: varchar("nip_ppk"),
	namaPpk: varchar("nama_ppk"),
	jabatanPpk: varchar("jabatan_ppk"),
	noSkPpk: varchar("no_sk_ppk"),
	kdPenyedia: numeric("kd_penyedia").notNull(),
	namaPenyedia: varchar("nama_penyedia"),
	npwpPenyedia: varchar("npwp_penyedia"),
	bentukUsahaPenyedia: varchar("bentuk_usaha_penyedia"),
	tipePenyedia: varchar("tipe_penyedia"),
	anggotaKso: varchar("anggota_kso"),
	wakilSahPenyedia: varchar("wakil_sah_penyedia"),
	jabatanWakilPenyedia: varchar("jabatan_wakil_penyedia"),
	namaRekBank: varchar("nama_rek_bank"),
	noRekBank: varchar("no_rek_bank"),
	namaPemilikRekBank: varchar("nama_pemilik_rek_bank"),
	nilaiKontrak: numeric("nilai_kontrak"),
	alasanUbahNilaiKontrak: varchar("alasan_ubah_nilai_kontrak"),
	alasanNilaiKontrak10Persen: varchar("alasan_nilai_kontrak_10_persen"),
	nilaiPdnKontrak: numeric("nilai_pdn_kontrak"),
	nilaiUmkKontrak: numeric("nilai_umk_kontrak"),
	jenisKontrak: varchar("jenis_kontrak"),
	informasiLainnya: varchar("informasi_lainnya"),
	statusKontrak: varchar("status_kontrak"),
	tglPenetapanStatusKontrak: timestamp("tgl_penetapan_status_kontrak", { mode: 'string' }),
	alasanPenetapanStatusKontrak: varchar("alasan_penetapan_status_kontrak"),
	apakahAddendum: varchar("apakah_addendum"),
	versiAddendum: integer("versi_addendum"),
	alasanAddendum: varchar("alasan_addendum"),
	id: numeric().default('nextval('seq_kontrak'::regclass)').primaryKey().notNull(),
	npwp16Penyedia: varchar("npwp_16_penyedia", { length: 20 }),
});

export const rupMasterSatker = pgTable("rup_master_satker", {
	kdSatker: numeric("kd_satker").primaryKey().notNull(),
	alamat: varchar({ length: 200 }),
	fax: varchar({ length: 50 }),
	jenisKlpd: varchar("jenis_klpd", { length: 50 }),
	jenisSatker: varchar("jenis_satker", { length: 50 }),
	kdKlpd: varchar("kd_klpd", { length: 20 }),
	kdSatkerStr: varchar("kd_satker_str", { length: 50 }),
	ketSatker: text("ket_satker"),
	kodeEselon: varchar("kode_eselon", { length: 50 }),
	kodepos: varchar({ length: 10 }),
	namaKlpd: varchar("nama_klpd", { length: 200 }),
	namaSatker: varchar("nama_satker", { length: 200 }),
	statusSatker: text("status_satker"),
	telepon: varchar({ length: 20 }),
});

export const rupPaketAnggaran = pgTable("rup_paket_anggaran", {
	asalDanaKlpd: varchar("asal_dana_klpd"),
	asalDanaSatker: varchar("asal_dana_satker"),
	jenisKlpd: varchar("jenis_klpd"),
	kdKegiatan: varchar("kd_kegiatan"),
	kdKlpd: varchar("kd_klpd"),
	kdKomponen: varchar("kd_komponen"),
	kdRup: varchar("kd_rup").notNull(),
	kdRupLokal: varchar("kd_rup_lokal"),
	kdSatker: numeric("kd_satker").notNull(),
	kdSatkerStr: varchar("kd_satker_str"),
	kdSubkegiatan: varchar("kd_subkegiatan"),
	mak: varchar(),
	namaKlpd: varchar("nama_klpd"),
	namaSatker: varchar("nama_satker"),
	pagu: numeric(),
	statusAktifRup: varchar("status_aktif_rup"),
	statusDeleteRup: varchar("status_delete_rup"),
	statusUmumkanRup: varchar("status_umumkan_rup"),
	sumberDana: varchar("sumber_dana"),
	tahunAnggaran: integer("tahun_anggaran"),
	tahunAnggaranDana: varchar("tahun_anggaran_dana"),
	id: numeric().default('nextval('seq_rup_paket_anggaran'::regclass)').primaryKey().notNull(),
	asalDana: varchar("asal_dana"),
	eventDate: timestamp("_event_date", { mode: 'string' }),
});

export const rupPaketLokasi = pgTable("rup_paket_lokasi", {
	detailLokasi: varchar("detail_lokasi"),
	jenisKlpd: varchar("jenis_klpd"),
	kabKota: varchar("kab_kota"),
	kdKabKota: integer("kd_kab_kota"),
	kdKlpd: varchar("kd_klpd"),
	kdProvinsi: integer("kd_provinsi"),
	kdRup: numeric("kd_rup").notNull(),
	kdSatker: integer("kd_satker").notNull(),
	kdSatkerStr: varchar("kd_satker_str"),
	namaKlpd: varchar("nama_klpd"),
	namaSatker: varchar("nama_satker"),
	provinsi: varchar(),
	tahunAnggaran: integer("tahun_anggaran").notNull(),
	id: numeric().default('nextval('seq_rup_paket_lokasi'::regclass)').primaryKey().notNull(),
	eventDate: timestamp("_event_date", { mode: 'string' }),
});

export const pencatatan = pgTable("pencatatan", {
	kdNontenderPct: numeric("kd_nontender_pct").primaryKey().notNull(),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	namaKlpd: varchar("nama_klpd"),
	jenisKlpd: varchar("jenis_klpd"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	namaSatker: varchar("nama_satker"),
	kdLpse: integer("kd_lpse"),
	kdPktDce: numeric("kd_pkt_dce"),
	kdRup: varchar("kd_rup"),
	namaPaket: varchar("nama_paket"),
	pagu: numeric(),
	totalRealisasi: numeric("total_realisasi"),
	nilaiPdnPct: numeric("nilai_pdn_pct"),
	nilaiUmkPct: numeric("nilai_umk_pct"),
	sumberDana: varchar("sumber_dana"),
	uraianPekerjaan: varchar("uraian_pekerjaan"),
	informasiLainnya: varchar("informasi_lainnya"),
	kategoriPengadaan: varchar("kategori_pengadaan"),
	mtdPemilihan: varchar("mtd_pemilihan"),
	buktiPembayaran: varchar("bukti_pembayaran"),
	statusNontenderPct: varchar("status_nontender_pct"),
	statusNontenderPctKet: varchar("status_nontender_pct_ket"),
	alasanPembatalan: varchar("alasan_pembatalan"),
	nipPpk: varchar("nip_ppk"),
	namaPpk: varchar("nama_ppk"),
	tglBuatPaket: timestamp("tgl_buat_paket", { mode: 'string' }),
	tglMulaiPaket: timestamp("tgl_mulai_paket", { mode: 'string' }),
	tglSelesaiPaket: timestamp("tgl_selesai_paket", { mode: 'string' }),
	eventDate: timestamp("_event_date", { mode: 'string' }),
});

export const rupPaketSwakelola = pgTable("rup_paket_swakelola", {
	jenisKlpd: varchar("jenis_klpd"),
	kdKlpd: varchar("kd_klpd"),
	kdKlpdPenyelenggara: varchar("kd_klpd_penyelenggara"),
	kdRup: numeric("kd_rup").primaryKey().notNull(),
	kdRupLokal: varchar("kd_rup_lokal"),
	kdSatker: numeric("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	namaKlpd: varchar("nama_klpd"),
	namaKlpdPenyelenggara: varchar("nama_klpd_penyelenggara"),
	namaPaket: varchar("nama_paket"),
	namaPpk: varchar("nama_ppk"),
	namaSatker: varchar("nama_satker"),
	namaSatkerPenyelenggara: varchar("nama_satker_penyelenggara"),
	nipPpk: varchar("nip_ppk"),
	pagu: numeric(),
	statusAktifRup: varchar("status_aktif_rup"),
	statusDeleteRup: varchar("status_delete_rup"),
	statusUmumkanRup: varchar("status_umumkan_rup"),
	tahunAnggaran: integer("tahun_anggaran"),
	tglAkhirPelaksanaanKontrak: timestamp("tgl_akhir_pelaksanaan_kontrak", { mode: 'string' }),
	tglAwalPelaksanaanKontrak: timestamp("tgl_awal_pelaksanaan_kontrak", { mode: 'string' }),
	tglBuatPaket: date("tgl_buat_paket"),
	tglPengumumanPaket: timestamp("tgl_pengumuman_paket", { mode: 'string' }),
	tipeSwakelola: varchar("tipe_swakelola"),
	uraianPekerjaan: varchar("uraian_pekerjaan"),
	usernamePpk: varchar("username_ppk"),
	volumePekerjaan: varchar("volume_pekerjaan"),
	eventDate: timestamp("_event_date", { mode: 'string' }),
}, (table) => [
	index("rup_paket_swakelola_terumumkan_tahun").using("btree", table.tahunAnggaran.asc().nullsLast().op("int4_ops")),
]);

export const rupPaketSwakelolaLokasi = pgTable("rup_paket_swakelola_lokasi", {
	detailLokasi: varchar("detail_lokasi"),
	jenisKlpd: varchar("jenis_klpd"),
	kabKota: varchar("kab_kota"),
	kdKabKota: varchar("kd_kab_kota"),
	kdKlpd: varchar("kd_klpd"),
	kdProvinsi: varchar("kd_provinsi"),
	kdRup: varchar("kd_rup"),
	kdSatker: integer("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	namaKlpd: varchar("nama_klpd"),
	namaSatker: varchar("nama_satker"),
	provinsi: varchar(),
	tahunAnggaran: integer("tahun_anggaran"),
	eventDate: timestamp("_event_date", { mode: 'string' }),
});

export const bast = pgTable("bast", {
	kdTender: numeric("kd_tender").notNull(),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	namaKlpd: varchar("nama_klpd"),
	jenisKlpd: varchar("jenis_klpd"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	namaSatker: varchar("nama_satker"),
	alamatSatker: varchar("alamat_satker"),
	kdLpse: integer("kd_lpse"),
	namaPaket: varchar("nama_paket"),
	noSppbj: varchar("no_sppbj"),
	noKontrak: varchar("no_kontrak"),
	tglKontrak: timestamp("tgl_kontrak", { mode: 'string' }),
	nilaiKontrak: numeric("nilai_kontrak"),
	namaPpk: varchar("nama_ppk"),
	nipPpk: varchar("nip_ppk"),
	jabatanPpk: varchar("jabatan_ppk"),
	noSkPpk: varchar("no_sk_ppk"),
	jabatanPenandatanganSk: varchar("jabatan_penandatangan_sk"),
	namaPenyedia: varchar("nama_penyedia"),
	alamatPenyedia: varchar("alamat_penyedia"),
	npwpPenyedia: varchar("npwp_penyedia"),
	wakilSahPenyedia: varchar("wakil_sah_penyedia"),
	jabatanWakilPenyedia: varchar("jabatan_wakil_penyedia"),
	noBast: varchar("no_bast"),
	tglBast: timestamp("tgl_bast", { mode: 'string' }),
	noBap: varchar("no_bap"),
	tglBap: timestamp("tgl_bap", { mode: 'string' }),
	besarPembayaran: numeric("besar_pembayaran"),
	progresPekerjaan: integer("progres_pekerjaan"),
	caraPembayaranKontrak: varchar("cara_pembayaran_kontrak"),
	statusKontrak: varchar("status_kontrak"),
	tglPenetapanStatusKontrak: timestamp("tgl_penetapan_status_kontrak", { mode: 'string' }),
	alasanPenetapanStatusKontrak: varchar("alasan_penetapan_status_kontrak"),
	apakahAddendum: varchar("apakah_addendum"),
	versiAddendum: integer("versi_addendum"),
	alasanAddendum: varchar("alasan_addendum"),
	id: numeric().default('nextval('seq_bast'::regclass)').primaryKey().notNull(),
});

export const kontrakNontender = pgTable("kontrak_nontender", {
	kdNontender: numeric("kd_nontender").notNull(),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	namaKlpd: varchar("nama_klpd"),
	jenisKlpd: varchar("jenis_klpd"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	namaSatker: varchar("nama_satker"),
	alamatSatker: varchar("alamat_satker"),
	kdLpse: integer("kd_lpse"),
	namaPaket: varchar("nama_paket"),
	mtdPengadaan: varchar("mtd_pengadaan"),
	lingkupPekerjaan: varchar("lingkup_pekerjaan"),
	noSppbj: varchar("no_sppbj"),
	noKontrak: varchar("no_kontrak"),
	tglKontrak: timestamp("tgl_kontrak", { mode: 'string' }),
	tglKontrakAwal: timestamp("tgl_kontrak_awal", { mode: 'string' }),
	tglKontrakAkhir: timestamp("tgl_kontrak_akhir", { mode: 'string' }),
	kotaKontrak: varchar("kota_kontrak"),
	nipPpk: varchar("nip_ppk"),
	namaPpk: varchar("nama_ppk"),
	jabatanPpk: varchar("jabatan_ppk"),
	noSkPpk: varchar("no_sk_ppk"),
	namaPenyedia: varchar("nama_penyedia"),
	npwpPenyedia: varchar("npwp_penyedia"),
	bentukUsahaPenyedia: varchar("bentuk_usaha_penyedia"),
	tipePenyedia: varchar("tipe_penyedia"),
	anggotaKso: varchar("anggota_kso"),
	wakilSahPenyedia: varchar("wakil_sah_penyedia"),
	jabatanWakilPenyedia: varchar("jabatan_wakil_penyedia"),
	namaRekBank: varchar("nama_rek_bank"),
	noRekBank: varchar("no_rek_bank"),
	namaPemilikRekBank: varchar("nama_pemilik_rek_bank"),
	nilaiKontrak: numeric("nilai_kontrak"),
	alasanUbahNilaiKontrak: varchar("alasan_ubah_nilai_kontrak"),
	alasanNilaiKontrak10Persen: varchar("alasan_nilai_kontrak_10_persen"),
	nilaiPdnKontrak: numeric("nilai_pdn_kontrak"),
	nilaiUmkKontrak: numeric("nilai_umk_kontrak"),
	jenisKontrak: varchar("jenis_kontrak"),
	informasiLainnya: varchar("informasi_lainnya"),
	statusKontrak: varchar("status_kontrak"),
	tglPenetapanStatusKontrak: timestamp("tgl_penetapan_status_kontrak", { mode: 'string' }),
	alasanPenetapanStatusKontrak: varchar("alasan_penetapan_status_kontrak"),
	apakahAddendum: varchar("apakah_addendum"),
	versiAddendum: integer("versi_addendum"),
	alasanAddendum: varchar("alasan_addendum"),
	id: numeric().default('nextval('seq_kontrak_nontender'::regclass)').primaryKey().notNull(),
	npwp16Penyedia: varchar("npwp16_penyedia", { length: 20 }),
});

export const rupPaket = pgTable("rup_paket", {
	alasanNonUkm: varchar("alasan_non_ukm"),
	jenisKlpd: varchar("jenis_klpd"),
	jenisPengadaan: varchar("jenis_pengadaan"),
	kdJenisPengadaan: varchar("kd_jenis_pengadaan"),
	kdKlpd: varchar("kd_klpd"),
	kdMetodePengadaan: varchar("kd_metode_pengadaan"),
	kdRup: numeric("kd_rup").primaryKey().notNull(),
	kdRupLokal: varchar("kd_rup_lokal"),
	kdRupSwakelola: varchar("kd_rup_swakelola"),
	kdSatker: numeric("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	metodePengadaan: varchar("metode_pengadaan"),
	namaKlpd: varchar("nama_klpd"),
	namaPaket: varchar("nama_paket"),
	namaPpk: varchar("nama_ppk"),
	namaSatker: varchar("nama_satker"),
	nipPpk: varchar("nip_ppk"),
	pagu: numeric(),
	spesifikasiPekerjaan: varchar("spesifikasi_pekerjaan"),
	statusAktifRup: boolean("status_aktif_rup"),
	statusDeleteRup: boolean("status_delete_rup"),
	statusKonsolidasi: varchar("status_konsolidasi"),
	statusPdn: varchar("status_pdn"),
	statusPradipa: varchar("status_pradipa"),
	statusUkm: varchar("status_ukm"),
	statusUmumkanRup: varchar("status_umumkan_rup"),
	tahunAnggaran: integer("tahun_anggaran"),
	tglAkhirKontrak: date("tgl_akhir_kontrak"),
	tglAkhirPemanfaatan: date("tgl_akhir_pemanfaatan"),
	tglAkhirPemilihan: date("tgl_akhir_pemilihan"),
	tglAwalKontrak: date("tgl_awal_kontrak"),
	tglAwalPemanfaatan: date("tgl_awal_pemanfaatan"),
	tglAwalPemilihan: date("tgl_awal_pemilihan"),
	tglBuatPaket: date("tgl_buat_paket"),
	tglPengumumanPaket: timestamp("tgl_pengumuman_paket", { mode: 'string' }),
	tipePaket: varchar("tipe_paket"),
	urarianPekerjaan: varchar("urarian_pekerjaan"),
	usernamePpk: varchar("username_ppk"),
	volumePekerjaan: varchar("volume_pekerjaan"),
	statusDikecualikan: varchar("status_dikecualikan"),
	alasanDikecualikan: varchar("alasan_dikecualikan"),
	tahunPertama: integer("tahun_pertama"),
	kdRupTahunPertama: numeric("kd_rup_tahun_pertama"),
	nomorKontrak: varchar("nomor_kontrak"),
	sppAspekEkonomi: boolean("spp_aspek_ekonomi"),
	sppAspekSosial: boolean("spp_aspek_sosial"),
	sppAspekLingkungan: boolean("spp_aspek_lingkungan"),
	kodeRupTahunPertama: numeric("kode_rup_tahun_pertama"),
	eventDate: timestamp("_event_date", { mode: 'string' }),
}, (table) => [
	index("rup_paket_penyedia_terumumkan_tahun").using("btree", table.tahunAnggaran.asc().nullsLast().op("int4_ops")),
]);

export const rupMasterInstansi = pgTable("rup_master_instansi", {
	id: varchar().primaryKey().notNull(),
	nama: varchar().notNull(),
	propId: numeric("prop_id"),
	kabupatenId: numeric("kabupaten_id"),
	alamat: varchar(),
	jenis: varchar(),
});

export const swakelolaRealisasi = pgTable("swakelola_realisasi", {
	kdSwakelolaPct: numeric("kd_swakelola_pct").notNull(),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	kdSatker: varchar("kd_satker"),
	kdLpse: integer("kd_lpse"),
	jenisRealisasi: varchar("jenis_realisasi"),
	noRealisasi: varchar("no_realisasi"),
	tglRealisasi: timestamp("tgl_realisasi", { mode: 'string' }),
	nilaiRealisasi: numeric("nilai_realisasi"),
	dokRealisasi: varchar("dok_realisasi"),
	ketRealisasi: varchar("ket_realisasi"),
	namaPelaksana: varchar("nama_pelaksana"),
	npwpPelaksana: varchar("npwp_pelaksana"),
	nipPpk: varchar("nip_ppk"),
	namaPpk: varchar("nama_ppk"),
	id: numeric().default('nextval('seq_swakelola_realisasi'::regclass)').primaryKey().notNull(),
});

export const swakelola = pgTable("swakelola", {
	kdSwakelolaPct: numeric("kd_swakelola_pct").primaryKey().notNull(),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	namaKlpd: varchar("nama_klpd"),
	jenisKlpd: varchar("jenis_klpd"),
	kdSatker: varchar("kd_satker"),
	kdSatkerStr: varchar("kd_satker_str"),
	namaSatker: varchar("nama_satker"),
	kdLpse: integer("kd_lpse"),
	kdPktDce: numeric("kd_pkt_dce"),
	kdRup: varchar("kd_rup"),
	namaPaket: varchar("nama_paket"),
	pagu: numeric(),
	totalRealisasi: numeric("total_realisasi"),
	nilaiPdnPct: numeric("nilai_pdn_pct"),
	nilaiUmkPct: numeric("nilai_umk_pct"),
	sumberDana: varchar("sumber_dana"),
	uraianPekerjaan: varchar("uraian_pekerjaan"),
	informasiLainnya: varchar("informasi_lainnya"),
	tipeSwakelola: varchar("tipe_swakelola"),
	tipeSwakelolaNama: varchar("tipe_swakelola_nama"),
	statusSwakelolaPct: varchar("status_swakelola_pct"),
	statusSwakelolaPctKet: varchar("status_swakelola_pct_ket"),
	alasanPembatalan: varchar("alasan_pembatalan"),
	nipPpk: varchar("nip_ppk"),
	namaPpk: varchar("nama_ppk"),
	tglBuatPaket: timestamp("tgl_buat_paket", { mode: 'string' }),
	tglMulaiPaket: timestamp("tgl_mulai_paket", { mode: 'string' }),
	tglSelesaiPaket: timestamp("tgl_selesai_paket", { mode: 'string' }),
});

export const pencatatanRealisasi = pgTable("pencatatan_realisasi", {
	kdNontenderPct: numeric("kd_nontender_pct").notNull(),
	tahunAnggaran: integer("tahun_anggaran"),
	kdKlpd: varchar("kd_klpd"),
	kdSatker: varchar("kd_satker"),
	kdLpse: integer("kd_lpse"),
	kategoriPengadaan: varchar("kategori_pengadaan"),
	mtdPemilihan: varchar("mtd_pemilihan"),
	jenisRealisasi: varchar("jenis_realisasi"),
	noRealisasi: varchar("no_realisasi"),
	tglRealisasi: timestamp("tgl_realisasi", { mode: 'string' }),
	nilaiRealisasi: numeric("nilai_realisasi"),
	dokRealisasi: varchar("dok_realisasi"),
	ketRealisasi: varchar("ket_realisasi"),
	namaPenyedia: varchar("nama_penyedia"),
	npwpPenyedia: varchar("npwp_penyedia"),
	nipPpk: varchar("nip_ppk"),
	namaPpk: varchar("nama_ppk"),
	id: numeric().default('nextval('seq_pencatatan_realisasi'::regclass)').primaryKey().notNull(),
	jenisPenyedia: varchar("jenis_penyedia"),
	namaKlpd: varchar("nama_klpd"),
	jenisKlpd: varchar("jenis_klpd"),
	eventDate: timestamp("_event_date", { mode: 'string' }),
	kdSatkerStr: varchar("kd_satker_str"),
	namaSatker: varchar("nama_satker"),
	namaLpse: varchar("nama_lpse"),
	kdPaketDce: numeric("kd_paket_dce"),
	kdRupPaket: numeric("kd_rup_paket"),
	namaPaket: varchar("nama_paket"),
	pagu: varchar(),
});

export const scheduledTasks = pgTable("scheduled_tasks", {
	taskName: text("task_name").notNull(),
	taskInstance: text("task_instance").notNull(),
	// TODO: failed to parse database type 'bytea'
	taskData: unknown("task_data"),
	executionTime: timestamp("execution_time", { withTimezone: true, mode: 'string' }).notNull(),
	picked: boolean().notNull(),
	pickedBy: text("picked_by"),
	lastSuccess: timestamp("last_success", { withTimezone: true, mode: 'string' }),
	lastFailure: timestamp("last_failure", { withTimezone: true, mode: 'string' }),
	consecutiveFailures: integer("consecutive_failures"),
	lastHeartbeat: timestamp("last_heartbeat", { withTimezone: true, mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	version: bigint({ mode: "number" }).notNull(),
}, (table) => [
	index("execution_time_idx").using("btree", table.executionTime.asc().nullsLast().op("timestamptz_ops")),
	index("last_heartbeat_idx").using("btree", table.lastHeartbeat.asc().nullsLast().op("timestamptz_ops")),
	primaryKey({ columns: [table.taskName, table.taskInstance], name: "scheduled_tasks_pkey"}),
]);

export const rupStrukturAnggaranKl = pgTable("rup_struktur_anggaran_kl", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaBarjas: bigint("belanja_barjas", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaModal: bigint("belanja_modal", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaNonpengadaanHibah: bigint("belanja_nonpengadaan_hibah", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaNonpengadaanLainnya: bigint("belanja_nonpengadaan_lainnya", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaNonpengadaanSosial: bigint("belanja_nonpengadaan_sosial", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaPegawai: bigint("belanja_pegawai", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaPengadaanHibah: bigint("belanja_pengadaan_hibah", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaPengadaanLainnya: bigint("belanja_pengadaan_lainnya", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	belanjaPengadaanSosial: bigint("belanja_pengadaan_sosial", { mode: "number" }),
	kdKlpd: varchar("kd_klpd").notNull(),
	kdSatker: numeric("kd_satker").notNull(),
	kdSatkerStr: varchar("kd_satker_str"),
	namaKlpd: varchar("nama_klpd"),
	namaSatker: varchar("nama_satker"),
	tahunAnggaran: integer("tahun_anggaran").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalBelanja: bigint("total_belanja", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalBelanjaHibah: bigint("total_belanja_hibah", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalBelanjaLainnya: bigint("total_belanja_lainnya", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalBelanjaSosial: bigint("total_belanja_sosial", { mode: "number" }),
}, (table) => [
	primaryKey({ columns: [table.kdKlpd, table.kdSatker, table.tahunAnggaran], name: "rup_struktur_anggaran_kl_pkey"}),
]);
